blank_issues_enabled: true
contact_links:
  - name: Ask question
    about: Ask a question about this project.
    url: https://github.com/clap-rs/clap/discussions/new
    # TODO: Question template (waiting for discussions template feature)
